name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'
    - name: Build with Gradle
      run: ./gradlew clean build desktop:deployLeikr -x test
      
    - name: Upload Leikr deploy
      uses: actions/upload-artifact@v2
      with:
        name: Leikr
        path: deploy
