name: Leikr Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'
    - name: Build with Gradle
      run: ./gradlew clean build desktop:deployLeikr -x test && ./gradlew javadoc
      
    - name: Upload Leikr deploy
      uses: actions/upload-artifact@v2
      with:
        name: Leikr
        path: deploy
    - name: Update Docs
      working-directory: ./core/build/docs
      run: |
        git init .
        git checkout -B gh-pages
        git config user.name "actions"
        git config user.email "actions@github.com"
        cp ../../../README.md .
        cp -R ../../../site/ .
        git add .
        git remote add origin https://${{github.repository_owner}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
        git push origin gh-pages --force
